services:
  route-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: route-optimizer
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs